version: "3.8"

services:
  # api:
  #   container_name: sisy-api
  #   build:
  #     context: .
  #     dockerfile: docker/api/Dockerfile # Correct path to the Dockerfile
  #     target: dev
  #   volumes:
  #     - .:/app:rw,delegated
  #   networks:
  #     - sisy_network
  #   ports:
  #     - 8181:8080
  #     - 2345:2345
  #   depends_on:
  #     - postgres
  postgres:
    container_name: sisy-db
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    networks:
      - sisy_network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  sisy_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
