package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/skanderphilipp/sisyApi/internal/domain/models"
)

// CreateStage is the resolver for the createStage field.
func (r *mutationResolver) CreateStage(ctx context.Context, input models.CreateStageInput) (*models.Stage, error) {
	panic(fmt.Errorf("not implemented: CreateStage - createStage"))
}

// StagesByVenue is the resolver for the stagesByVenue field.
func (r *queryResolver) StagesByVenue(ctx context.Context, venueID uuid.UUID) ([]*models.Stage, error) {
	panic(fmt.Errorf("not implemented: StagesByVenue - stagesByVenue"))
}
