package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/blnto/blnto_service/internal/domain/models"
	"github.com/google/uuid"
)

// CreateTimetableEntry is the resolver for the createTimetableEntry field.
func (r *mutationResolver) CreateTimetableEntry(ctx context.Context, input models.CreateTimetableEntryInput) (*models.TimetableEntry, error) {
	panic(fmt.Errorf("not implemented: CreateTimetableEntry - createTimetableEntry"))
}

// DeleteTimeTableEntry is the resolver for the deleteTimeTableEntry field.
func (r *mutationResolver) DeleteTimeTableEntry(ctx context.Context, input models.DeleteTimetableEntryInput) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTimeTableEntry - deleteTimeTableEntry"))
}

// GetTimetableEntriesByEventID is the resolver for the getTimetableEntriesByEventID field.
func (r *queryResolver) GetTimetableEntriesByEventID(ctx context.Context, eventID uuid.UUID) (*models.TimetableEntryConnection, error) {
	panic(fmt.Errorf("not implemented: GetTimetableEntriesByEventID - getTimetableEntriesByEventID"))
}

// TimetableByEventID is the resolver for the timetableByEventID field.
func (r *queryResolver) TimetableByEventID(ctx context.Context, eventID uuid.UUID) ([]*models.TimetableEntry, error) {
	panic(fmt.Errorf("not implemented: TimetableByEventID - timetableByEventID"))
}
