package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/skanderphilipp/sisyApi/internal/domain/models"
)

// CreateTimetableEntry is the resolver for the createTimetableEntry field.
func (r *mutationResolver) CreateTimetableEntry(ctx context.Context, input models.CreateTimetableEntryInput) (*models.TimetableEntry, error) {
	panic(fmt.Errorf("not implemented: CreateTimetableEntry - createTimetableEntry"))
}

// TimetableByEventID is the resolver for the timetableByEventID field.
func (r *queryResolver) TimetableByEventID(ctx context.Context, eventID uuid.UUID) ([]*models.TimetableEntry, error) {
	panic(fmt.Errorf("not implemented: TimetableByEventID - timetableByEventID"))
}
