package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/skanderphilipp/sisyApi/internal/domain/models"
)

// CreateVenue is the resolver for the createVenue field.
func (r *mutationResolver) CreateVenue(ctx context.Context, input models.CreateVenueInput) (*models.Venue, error) {
	panic(fmt.Errorf("not implemented: CreateVenue - createVenue"))
}

// ListVenues is the resolver for the listVenues field.
func (r *queryResolver) ListVenues(ctx context.Context, first *int, after *string) (*models.VenueConnection, error) {
	panic(fmt.Errorf("not implemented: ListVenues - listVenues"))
}

// AllVenues is the resolver for the allVenues field.
func (r *queryResolver) AllVenues(ctx context.Context) ([]*models.Venue, error) {
	panic(fmt.Errorf("not implemented: AllVenues - allVenues"))
}

// Venue is the resolver for the venue field.
func (r *queryResolver) Venue(ctx context.Context, id uuid.UUID) (*models.Venue, error) {
	panic(fmt.Errorf("not implemented: Venue - venue"))
}
