package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/blnto/blnto_service/internal/domain/models"
	"github.com/google/uuid"
)

// CreateVenue is the resolver for the createVenue field.
func (r *mutationResolver) CreateVenue(ctx context.Context, input models.CreateVenueInput) (*models.Venue, error) {
	newVenue := models.Venue{
		Name:        input.Name,
		Description: input.Description,
	}

	if input.Stages != nil {
		var stages []*models.Stage
		for _, stageInput := range input.Stages {
			// Assuming that models.CreateVenueStageInput and models.Stage have similar fields
			stage := &models.Stage{
				Name: stageInput.Name,
			}
			stages = append(stages, stage)
			newVenue.Stages = stages
		}
	}

	// Call the repository function to create the artist
	createdVenue, err := r.venueService.Save(ctx, &newVenue)
	if err != nil {
		return nil, err
	}

	return createdVenue, nil
}

// UpdateVenue is the resolver for the updateVenue field.
func (r *mutationResolver) UpdateVenue(ctx context.Context, id uuid.UUID, input models.CreateVenueInput) (*models.Venue, error) {
	panic(fmt.Errorf("not implemented: UpdateVenue - updateVenue"))
}

// DeleteVenue is the resolver for the deleteVenue field.
func (r *mutationResolver) DeleteVenue(ctx context.Context, id uuid.UUID) (*models.Venue, error) {
	panic(fmt.Errorf("not implemented: DeleteVenue - deleteVenue"))
}

// ListVenues is the resolver for the listVenues field.
func (r *queryResolver) ListVenues(ctx context.Context, first *int, after *string) (*models.VenueConnection, error) {
	// Set default values if nil
	var limit int
	if first == nil {
		limit = 10 // Default limit value
	} else {
		limit = *first
	}

	var cursor string
	if after != nil {
		cursor = *after
	}

	// Assuming you have an artist repository instance (artistRepo)
	venues, nextCursor, err := r.venueService.FindAllByCursor(ctx, cursor, limit)
	if err != nil {
		return nil, fmt.Errorf("error fetching artists: %v", err)
	}

	// Map artists to GraphQL edges

	edges := make([]*models.VenueEdge, len(venues))

	for i, venue := range venues {
		cursorStr := venue.ID.String() // Convert UUID to string
		edges[i] = &models.VenueEdge{
			Node:   venue,
			Cursor: cursorStr, // Assuming ID is a UUID
		}
	}

	// Construct ArtistConnection
	hasNextPage := len(edges) == limit
	venueConnection := &models.VenueConnection{
		Edges: edges,
		PageInfo: &models.PageInfo{
			EndCursor:   &nextCursor,
			HasNextPage: &hasNextPage,
		},
	}

	return venueConnection, nil
}

// GetVenue is the resolver for the getVenue field.
func (r *queryResolver) GetVenue(ctx context.Context, id uuid.UUID) (*models.Venue, error) {
	panic(fmt.Errorf("not implemented: GetVenue - getVenue"))
}
